<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_special-page',
		'title' => 'Special page',
		'fields' => array (
			array (
				'key' => 'field_5b2ba7290a7eb',
				'label' => 'Headers',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5b2b9c59e33d8',
				'label' => 'Header H3',
				'name' => 'header_h3',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Main header',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2b9d27e33d9',
				'label' => 'header H3 description',
				'name' => 'header_h3_description',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Main header description',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2b9f147ee47',
				'label' => 'Header H4',
				'name' => 'header_h4',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Second header',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2b9f3d7ee48',
				'label' => 'header H4 description',
				'name' => 'header_h4_description',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Second header description',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2b9f637ee49',
				'label' => 'Header H5',
				'name' => 'header_h5',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Third header',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2b9f6e7ee4a',
				'label' => 'header H5 description',
				'name' => 'header_h5_description',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Third header description',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2ba6ff0a7ea',
				'label' => 'Main slider',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5b2ba2da663ac',
				'label' => 'Main slider image 1',
				'name' => 'main_slider_image_1',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5b2ba47b663af',
				'label' => 'Main slider image 2',
				'name' => 'main_slider_image_2',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5b2ba47a663ae',
				'label' => 'Main slider image 3',
				'name' => 'main_slider_image_3',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5b2ba479663ad',
				'label' => 'Main slider image 4',
				'name' => 'main_slider_image_4',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5b3ba479663ad',
				'label' => 'Main slider image 5',
				'name' => 'main_slider_image_5',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5b4ba479663ad',
				'label' => 'Main slider image 6',
				'name' => 'main_slider_image_6',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5b2ba85e9cb1b',
				'label' => 'Features',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5b2ba8a09cb1c',
				'label' => 'Feature 1',
				'name' => 'feature_1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Feature',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2ba9679cb1d',
				'label' => 'Feature 2',
				'name' => 'feature_2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Feature',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2ba9789cb1e',
				'label' => 'Feature 3',
				'name' => 'feature_3',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Feature',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2ba9849cb1f',
				'label' => 'Feature 4',
				'name' => 'feature_4',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Feature',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2ba98d9cb20',
				'label' => 'Feature 5',
				'name' => 'feature_5',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Feature',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2baa327d7b9',
				'label' => 'Feature 6',
				'name' => 'feature_6',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Feature',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2baa3d7d7ba',
				'label' => 'Feature 7',
				'name' => 'feature_7',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Feature',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2baa4e7d7bb',
				'label' => 'Feature 8',
				'name' => 'feature_8',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Feature',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2baa757d7bc',
				'label' => 'Feature 9',
				'name' => 'feature_9',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Feature',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2baa807d7bd',
				'label' => 'Feature 10',
				'name' => 'feature_10',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Feature',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2baa8b7d7be',
				'label' => 'Feature 11',
				'name' => 'feature_11',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Feature',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2baa9a7d7bf',
				'label' => 'Feature 12',
				'name' => 'feature_12',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Feature',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2baab07d7c0',
				'label' => 'Feature 13',
				'name' => 'feature_13',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Feature',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2baac47d7c1',
				'label' => 'Feature 14',
				'name' => 'feature_14',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Feature',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2babe9a9317',
				'label' => 'Call',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5b2bac13a9318',
				'label' => 'Call Details',
				'name' => 'call_details',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Call Details',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
            array (
                'key' => 'field_5b3bac13a9318',
                'label' => 'Call Phone Number',
                'name' => 'call_phone_number',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => 'Call Phone Number',
                'prepend' => '',
                'append' => '',
                'formatting' => 'none',
                'maxlength' => '',
            ),
			array (
				'key' => 'field_5b2bad48a9319',
				'label' => 'Videos',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5b2bad72a931a',
				'label' => 'Video URL 1 ',
				'name' => 'video_url_1',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'https://www.youtube.com/embed/',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2baf25a931b',
				'label' => 'Video URL 2',
				'name' => 'video_url_2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'https://www.youtube.com/embed/',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2bb0aadd93a',
				'label' => 'Image Section',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5b2bb522dd93b',
				'label' => 'Image header H2',
				'name' => 'image_header_h2',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2bb56fdd93c',
				'label' => 'Image header H3',
				'name' => 'image_header_h3',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2bb5a2dd93d',
				'label' => 'Image header H5',
				'name' => 'image_header_h5',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2bb5f1dd93e',
				'label' => 'Image Tel Text',
				'name' => 'image_tel_text',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2bb620dd93f',
				'label' => 'Image Tel Number',
				'name' => 'image_tel_number',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2bb677dd941',
				'label' => 'Image Slogan',
				'name' => 'image_slogan',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2bb78330c65',
				'label' => 'Second Slider',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5b2bb7b730c66',
				'label' => 'Second slider image 1',
				'name' => 'second_slider_image_1',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5b2bb7db30c67',
				'label' => 'Second slider image 2',
				'name' => 'second_slider_image_2',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5b2bb80230c68',
				'label' => 'Second slider image 3',
				'name' => 'second_slider_image_3',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5b2bb80b30c69',
				'label' => 'Second slider image 4',
				'name' => 'second_slider_image_4',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5b2bb81530c6a',
				'label' => 'Second slider image 5',
				'name' => 'second_slider_image_5',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5b2bb81f30c6b',
				'label' => 'Second slider image 6',
				'name' => 'second_slider_image_6',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5b2bb82e30c6c',
				'label' => 'Second slider image 7',
				'name' => 'second_slider_image_7',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5b2bb83930c6d',
				'label' => 'Second slider image 8',
				'name' => 'second_slider_image_8',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5b2bb84430c6e',
				'label' => 'CTA',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5b2bb85230c6f',
				'label' => 'CTA Slogan',
				'name' => 'cta_slogan',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b2bb87130c70',
				'label' => 'CTA BG Image',
				'name' => 'cta_bg_image',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_5b2bb88d30c71',
				'label' => 'CTA Tel Number',
				'name' => 'cta_tel_number',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'special',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
